### ISSUE TITLE
Best way to get battle-haxe to work with armory?

### ISSUE THREAD

**Issue by mbmattos1113** [AlonTzarafi/battle-haxe#1]
I'm trying out the armory game engine for blender, which uses haxe for scripting. How can i get completion for it's API?
https://armory3d.org

**Comment by AlonTzarafi** [comment]
For completion to work, you need a .hxml file in the root of the project containing valid arguments to the "haxe" compiler command.

You just need to know the exact arguments armory uses when it compiles the Haxe files.
Haxe can use pretty much the same arguments for compilation and completion.

You could ask the armory guys for it, or try to find something from an armory project's config file.
Unlike for example OpenFL that uses a text file config "project.xml", it seems that in armory the config is inside the blender file so you need to have armory installed and know a bit more about it to look deeper. Or track how they compile Haxe files in their source files.

**Comment by mbmattos1113** [comment]
I just got the correct file with the armory guys, but it seems like i can't get autocomplete still. When i start typing, it compiles and saves all the time, and returns this:


`Haxe completion failed. Haxe returned:
/bin/bash: -c: line 0: syntax error near unexpected token ('
/bin/bash: -c: line 0: haxe --connect 6000 --cwd /home/marlon/Software/blender/projects/2dtest/ -cp /HDD/My-Files/Software/blender/Program/armsdk/Kha/Sources -cp /HDD/My-Files/Software/blender/Program/armsdk/Kha/Backends/Krom -cp /HDD/My-Files/Software/blender/projects/2dtest/Sources -cp /HDD/My-Files/Software/blender/Program/armsdk/armory/Sources -cp /HDD/My-Files/Software/blender/Program/armsdk/iron/Sources -cp /HDD/My-Files/Software/blender/Program/armsdk/lib/haxebullet/Sources -cp /HDD/My-Files/Software/blender/Program/armsdk/armory -cp /HDD/My-Files/Software/blender/Program/armsdk/iron -cp /HDD/My-Files/Software/blender/Program/armsdk/lib/haxebullet -D /HDD/My-Files/Software/blender/Program/armsdk/armory -D /HDD/My-Files/Software/blender/Program/armsdk/iron -D /HDD/My-Files/Software/blender/Program/armsdk/lib/haxebullet -D arm_deferred -D arm_csm -D rp_hdr -D rp_renderer=Deferred -D rp_shadowmap -D rp_shadowmap_cascade=1024 -D rp_shadowmap_cube=512 -D rp_background=World -D rp_render_to_texture -D rp_compositornodes -D rp_antialiasing=SMAA -D rp_supersampling=1 -D rp_ssgi=SSAO -D rp_gi=Off -D arm_physics -D arm_bullet -D arm_noembed -D arm_soundcompress -D arm_skin -D arm_particles_gpu -D arm_particles -D sys_krom -D sys_g1 -D sys_g2 -D sys_g3 -D sys_g4 -D sys_a1 -D sys_a2 -D kha_js -D kha_krom -D kha_krom_js -D kha_opengl -D kha_g1 -D kha_g2 -D kha_g3 -D kha_g4 -D kha_a1 -D kha_a2 -D kha -D kha_version=1810 -D kha_project_name=2d -js krom/krom.js.temp armory.trait.physics.bullet.PhysicsWorld --macro keep('armory.trait.physics.bullet.PhysicsWorld') armory.trait.physics.bullet.RigidBody --macro keep('armory.trait.physics.bullet.RigidBody') arm.node.PlayerMove --macro keep('arm.node.PlayerMove') -main Main --display /home/marlon/Software/blender/projects/2dtest/aaaa.hx@30@'
 (No changes need to be saved)`

**Comment by AlonTzarafi** [comment]
Hi @mbmattos1113 
It seems like an issue with bash trying and failing to interpret special characters in
`--macro keep('blah')`

I never did any checking for those special characters... oops

Here's an update that should fix it:
9aa29001dfc8ffef1646ef6128f77e1413981b03

Does it work for you?

**Comment by mbmattos1113** [comment]
It doesn't return the same verbose message, but i still don't have autocompletion (apart from repeating stuff already written in the document, which company does already)

**Comment by AlonTzarafi** [comment]
That's really strange because by default I disallow other backends to run even if battle-haxe fails so the default company completion shouldn't happen.

Did you use the use-package config block as it is in the readme?

Also, company has a diagnostics function. You can press `M-x company-diag` in your haxe file.
Which company backend does it say it tried to complete with?

**Comment by mbmattos1113** [comment]
If i try to write "extends", company-diag returns this:
` Emacs 26.1 (x86_64-pc-linux-gnu) of 2019-02-03 on zam904
Company 0.9.10
company-backends: (battle-haxe-company-backend company-irony company-bbdb company-eclim company-semantic company-clang company-xcode company-cmake company-capf company-files
			     (company-dabbrev-code company-gtags company-etags company-keywords)
			     company-oddmuse company-dabbrev)
Used backend: battle-haxe-company-backend
Major mode: haxe-mode
Prefix: #("exten" 0 1
  (fontified t face font-lock-type-face)
  1 2
  (fontified t face font-lock-type-face)
  2 3
  (fontified t face font-lock-type-face)
  3 4
  (fontified t face font-lock-type-face)
  4 5
  (fontified t face font-lock-type-face))
Completions: none `

also, armory specific completion still doesn't work, even with the .hxml file on the project root. I'm using the package from melpa, is that what i should use?

**Comment by AlonTzarafi** [comment]
Hi. I'm sorry I wasn't able to help you before but I can try again now.
Using the package from melpa is definitely the easiest way yeah.
The company-diag output above confirms battle-haxe was used but there were no completions. Actually in this situation right now, I get no completions myself. But that's because Haxe is always evolving. Right now I have Haxe 4.0.5 installed which is newer than the one most of battle-haxe was built on. I need to tweak my package to accommodate some changes they made to "compiler services" completions to make everything work.
However, most of the completion stuff still works well in battle-haxe and hasn't changed. Basic usage like:
`this.`
or
`someObject.`
still works good like always. Can you get any completions with armory at all?

**Comment by AlonTzarafi** [comment]
I'm closing this issue for now since it's unclear what the current issue is or how to proceed. However, if you still encounter any problems feel free to open a new issue on this topic.
